// AUTO-GENERATED from Ashby's own job-board bundle (frontend_non_user).
// Recovered by decompiling the precompiled GraphQL ASTs, then re-printing with graphql-js.
// These are the exact operations jobs.ashbyhq.com sends, so our requests are wire-identical
// to a real applicant's browser. Do not hand-edit: re-run tools/extract-ashby-ops.ts.

export const ASHBY_OPS = {
  ApiJobPosting: "query ApiJobPosting($organizationHostedJobsPageName: String!, $jobPostingId: String!) {\n  jobPosting(\n    organizationHostedJobsPageName: $organizationHostedJobsPageName\n    jobPostingId: $jobPostingId\n  ) {\n    id\n    title\n    departmentName\n    departmentExternalName\n    locationName\n    locationAddress\n    workplaceType\n    employmentType\n    descriptionHtml\n    isListed\n    isConfidential\n    teamNames\n    applicationForm {\n      ...FormRenderParts\n    }\n    surveyForms {\n      ...FormRenderParts\n    }\n    secondaryLocationNames\n    compensationTierSummary\n    compensationTiers {\n      id\n      title\n      tierSummary\n    }\n    applicationDeadline\n    compensationTierGuideUrl\n    scrapeableCompensationSalarySummary\n    compensationPhilosophyHtml\n    applicationLimitCalloutHtml\n    shouldAskForTextingConsent\n    shouldAskForWhatsAppConsent\n    candidateTextingPrivacyPolicyUrl\n    candidateTextingTermsAndConditionsUrl\n    legalEntityNameForTextingConsent\n    automatedProcessingLegalNotice {\n      automatedProcessingLegalNoticeRuleId\n      automatedProcessingLegalNoticeHtml\n    }\n  }\n}\n\nfragment JSONBoxParts on JSONBox {\n  value\n}\n\nfragment FileParts on File {\n  id\n  filename\n}\n\nfragment FormFieldEntryParts on FormFieldEntry {\n  id\n  field\n  fieldValue {\n    ... on JSONBox {\n      ...JSONBoxParts\n    }\n    ... on File {\n      ...FileParts\n    }\n    ... on FileList {\n      files {\n        ...FileParts\n      }\n    }\n  }\n  isRequired\n  descriptionHtml\n  isHidden\n}\n\nfragment FormRenderParts on FormRender {\n  id\n  formControls {\n    identifier\n    title\n  }\n  errorMessages\n  formErrors {\n    message\n    fieldEntryId\n  }\n  sections {\n    title\n    descriptionHtml\n    fieldEntries {\n      ...FormFieldEntryParts\n    }\n    isHidden\n  }\n  sourceFormDefinitionId\n}",

  ApiSetFormValue: "mutation ApiSetFormValue($organizationHostedJobsPageName: String!, $formRenderIdentifier: String!, $path: String!, $value: JSON, $formDefinitionIdentifier: String) {\n  setFormValue(\n    organizationHostedJobsPageName: $organizationHostedJobsPageName\n    formRenderIdentifier: $formRenderIdentifier\n    path: $path\n    value: $value\n    formDefinitionIdentifier: $formDefinitionIdentifier\n  ) {\n    ...FormRenderParts\n  }\n}\n\nfragment JSONBoxParts on JSONBox {\n  value\n}\n\nfragment FileParts on File {\n  id\n  filename\n}\n\nfragment FormFieldEntryParts on FormFieldEntry {\n  id\n  field\n  fieldValue {\n    ... on JSONBox {\n      ...JSONBoxParts\n    }\n    ... on File {\n      ...FileParts\n    }\n    ... on FileList {\n      files {\n        ...FileParts\n      }\n    }\n  }\n  isRequired\n  descriptionHtml\n  isHidden\n}\n\nfragment FormRenderParts on FormRender {\n  id\n  formControls {\n    identifier\n    title\n  }\n  errorMessages\n  formErrors {\n    message\n    fieldEntryId\n  }\n  sections {\n    title\n    descriptionHtml\n    fieldEntries {\n      ...FormFieldEntryParts\n    }\n    isHidden\n  }\n  sourceFormDefinitionId\n}",

  ApiSetFormValueToFile: "mutation ApiSetFormValueToFile($organizationHostedJobsPageName: String!, $formRenderIdentifier: String!, $path: String!, $fileHandle: String, $formDefinitionIdentifier: String) {\n  setFormValueToFile(\n    organizationHostedJobsPageName: $organizationHostedJobsPageName\n    formRenderIdentifier: $formRenderIdentifier\n    path: $path\n    fileHandle: $fileHandle\n    formDefinitionIdentifier: $formDefinitionIdentifier\n  ) {\n    ...FormRenderParts\n  }\n}\n\nfragment JSONBoxParts on JSONBox {\n  value\n}\n\nfragment FileParts on File {\n  id\n  filename\n}\n\nfragment FormFieldEntryParts on FormFieldEntry {\n  id\n  field\n  fieldValue {\n    ... on JSONBox {\n      ...JSONBoxParts\n    }\n    ... on File {\n      ...FileParts\n    }\n    ... on FileList {\n      files {\n        ...FileParts\n      }\n    }\n  }\n  isRequired\n  descriptionHtml\n  isHidden\n}\n\nfragment FormRenderParts on FormRender {\n  id\n  formControls {\n    identifier\n    title\n  }\n  errorMessages\n  formErrors {\n    message\n    fieldEntryId\n  }\n  sections {\n    title\n    descriptionHtml\n    fieldEntries {\n      ...FormFieldEntryParts\n    }\n    isHidden\n  }\n  sourceFormDefinitionId\n}",

  ApiCreateFileUploadHandle: "mutation ApiCreateFileUploadHandle($organizationHostedJobsPageName: String!, $fileUploadContext: FileUploadContext!, $filename: String!, $contentType: String!, $contentLength: Int!) {\n  fileUploadHandle: createFileUploadHandle(\n    organizationHostedJobsPageName: $organizationHostedJobsPageName\n    fileUploadContext: $fileUploadContext\n    filename: $filename\n    contentType: $contentType\n    contentLength: $contentLength\n  ) {\n    handle\n    url\n    fields\n  }\n}",

  ApiSubmitSingleApplicationFormAction: "mutation ApiSubmitSingleApplicationFormAction($organizationHostedJobsPageName: String!, $jobPostingId: String!, $formRenderIdentifier: String!, $formDefinitionIdentifier: String, $actionIdentifier: String!, $recaptchaToken: String!, $sourceAttributionCode: String, $viewedAutomatedProcessingLegalNoticeRuleId: String, $deviceFingerprint: String, $applicationRequestId: String) {\n  submitApplicationFormAction: submitSingleApplicationFormAction(\n    organizationHostedJobsPageName: $organizationHostedJobsPageName\n    jobPostingId: $jobPostingId\n    formRenderIdentifier: $formRenderIdentifier\n    formDefinitionIdentifier: $formDefinitionIdentifier\n    actionIdentifier: $actionIdentifier\n    recaptchaToken: $recaptchaToken\n    sourceAttributionCode: $sourceAttributionCode\n    viewedAutomatedProcessingLegalNoticeRuleId: $viewedAutomatedProcessingLegalNoticeRuleId\n    deviceFingerprint: $deviceFingerprint\n    applicationRequestId: $applicationRequestId\n  ) {\n    applicationFormResult {\n      ... on FormRender {\n        ...FormRenderParts\n      }\n      ... on FormSubmitSuccess {\n        _\n      }\n    }\n    messages {\n      blockMessageForCandidateHtml\n    }\n  }\n}\n\nfragment JSONBoxParts on JSONBox {\n  value\n}\n\nfragment FileParts on File {\n  id\n  filename\n}\n\nfragment FormFieldEntryParts on FormFieldEntry {\n  id\n  field\n  fieldValue {\n    ... on JSONBox {\n      ...JSONBoxParts\n    }\n    ... on File {\n      ...FileParts\n    }\n    ... on FileList {\n      files {\n        ...FileParts\n      }\n    }\n  }\n  isRequired\n  descriptionHtml\n  isHidden\n}\n\nfragment FormRenderParts on FormRender {\n  id\n  formControls {\n    identifier\n    title\n  }\n  errorMessages\n  formErrors {\n    message\n    fieldEntryId\n  }\n  sections {\n    title\n    descriptionHtml\n    fieldEntries {\n      ...FormFieldEntryParts\n    }\n    isHidden\n  }\n  sourceFormDefinitionId\n}",
} as const;

export type AshbyOpName = keyof typeof ASHBY_OPS;
